/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountBalance: typeof import('./src/components/AccountBalance.vue')['default']
    AccountCard: typeof import('./src/components/AccountCard.vue')['default']
    AccountTabs: typeof import('./src/components/AccountTabs.vue')['default']
    AddTransactionDialog: typeof import('./src/components/AddTransactionDialog.vue')['default']
    AppToolbar: typeof import('./src/components/AppToolbar.vue')['default']
    FilterBar: typeof import('./src/components/FilterBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransactionTable: typeof import('./src/components/TransactionTable.vue')['default']
  }
}
